version: '3.8'

services:
  go-server:
    build:
      context: .
    # dockerfile: ./go-server/Dockerfile.go
      dockerfile: Dockerfile.go
    container_name: go-server
    ports:
      - "8080:8080"
    networks:
      - weather-net
    restart: always

  python-bot:
    build:
      context: .
      dockerfile: ./python-bot/Dockerfile.bot
    container_name: python-bot
    environment:
      - TELEGRAM_API_KEY=your_telegram_bot_api_key
    depends_on:
      - go-server
    networks:
      - weather-net
    restart: always

  web-app:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: web-app
    ports:
      - "80:80"
    networks:
      - weather-net
    restart: always

networks:
  weather-net:
    driver: bridge
